export const DEFAULT_FEATURE_FLAGS = {
  ENABLE_REACTIONS: true,
  ENABLE_REPLIES: true,
  ENABLE_MESSAGE_EDITING: true,
  ENABLE_MESSAGE_DELETION: true,
  ENABLE_FILE_ATTACHMENTS: true,
  ENABLE_READ_RECEIPTS: true,
  ENABLE_PAGINATION: true,
  ENABLE_PRESENCE_INDICATORS: true,
  ENABLE_TYPING_INDICATORS: true,
};

export type FeatureFlags = typeof DEFAULT_FEATURE_FLAGS;
